### ISSUE TITLE
想问下，这个日志是在哪打印的，谢谢

### ISSUE THREAD

**Issue by jeffmingup** [yuyuanshifu/minio-breakpoint-upload#37]
![image](https://user-images.githubusercontent.com/28745363/197749034-a7989c3c-74c2-42d2-8fbe-de0d81ea650c.png)
这个是在minio服务端打印的，还是golang代码里面打印的啊

**Comment by yuyuanshifu** [comment]
是minio服务端打印的

**Comment by jeffmingup** [comment]
> 是minio服务端打印的

收到，谢谢，我再找找是哪个地方设置的，我用docker启动的，找了半天文档没看到在哪能设置。。。

**Comment by jeffmingup** [comment]
> > 是minio服务端打印的
> 
> 收到，谢谢，我再找找是哪个地方设置的，我用docker启动的，找了半天文档没看到在哪能设置。。。

找到了，原来是用mc客户端打印的（mc  admin trace -v -a minio），谢谢老哥
